---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: init
          image: postgres:15.0
          command: [ "bash", "-c" ]
          args:
            - |
              #create archive directory
              mkdir -p /data/archive && chown -R 999:999 /data/archive
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      containers:
        - name: postgres
          image: postgres:15.0
          args: ["-c", "config_file=/config/postgresql.conf"]
          ports:
            - containerPort: 5432
              name: database
          envFrom:
            - configMapRef:
                name: db-configmap
          env:
            - name: PGDATA
              value: "/data/pgdata"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: DB_NAME
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: db-configmap
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Mi