apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: db
  labels:
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  clusterIP: None
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: db-external
  namespace: db
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
