---
apiVersion: v1
kind: Secret
metadata:
  name: ll-secrets
  namespace: littleleague
type: Opaque
stringData:
  LL_DB_PASSWORD: "littleleague"
  DB_PASSWORD: 'postgres'
  SPRING_DATASOURCE_USERNAME: "littleleague"
  SPRING_DATASOURCE_PASSWORD: "littleleague"